/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://goiryswmizat3j2l5sk5ubkite.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qkvmzvssqrembfzru44moky3ne",
    "aws_cognito_identity_pool_id": "us-east-1:e279ddc0-c399-4d95-b903-0d283c74ae37",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1D92r38cA",
    "aws_user_pools_web_client_id": "1dvt6at9cbb3eonansf31205vc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "react-amplified-storage31429-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
